#!/usr/bin/env bash
# =========================================================================== #
# Description: Portable task manager for the command line.
# Command:     bash todo

# ERROR HANDLERS ============================================================ #

set -euo pipefail
set -o errtrace

die() {
	local code="${1:-1}"
	local desc="${2:-An unknown error has occurred.}"
	local line_no="${3:+, line $3}"

	printf "ERROR: %s\n" "$desc" >&2
	if [[ "$code" -eq 2 ]]; then
		printf "Try 'bash todo help' for more information.\n" >&2
	else
		printf "--> %s%s\n" "${FUNCNAME[@]:1:-1}" "$line_no" >&2
	fi
	exit "$code"
}

trap 'die 1 "Command failed unexpectedly." "$LINENO"' ERR

# GLOBALS =================================================================== #

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DATA_DIR="${DATA_DIR:-$SCRIPT_DIR}"
readonly TODO_FILE="${DATA_DIR}/todo.txt"
TASK_COUNT=0
INDEX_WIDTH=1

declare -gA UI
if [[ -n "${NO_COLOR:-}" ]]; then
	UI[ADD]="[+]"
	UI[DEL]="[-]"
	UI[DONE]="[x]"
	UI[UNDO]="[ ]"
	UI[SKIP]=">>"
else
	UI[ADD]="\U00002795"  # ➕
	UI[DEL]="\U0001F5D1"  # 🗑️
	UI[DONE]="\U00002705" # ✅
	UI[UNDO]="\U000021A9" # ↩️
	UI[SKIP]="\U000023ED" # ⏭️
fi

# HELPERS =================================================================== #

init_storage() {
	[[ -d "$DATA_DIR" ]] || die 1 "No directory found at ${DATA_DIR}."
	touch "$TODO_FILE"   || die 1 "Cannot create todo.txt inside ${DATA_DIR}."
	TASK_COUNT="$(wc -l < "$TODO_FILE")"
	INDEX_WIDTH="${#TASK_COUNT}"
}

is_todo_empty() {
	if [[ ! -s "$TODO_FILE" ]]; then
		printf "Your todo.txt file is empty!\n"; exit 0
	else return 0; fi
}

validate_index() {
	local index="$1"
	if [[ ! "$index" =~ ^[0-9]+$ ]]; then
		printf "%s '%s' is not a number. Skipping.\n" "${UI[SKIP]}" "$index"; return 1
	elif [[ "$index" -eq 0 ]]; then
		printf "%s Task index must be greater than zero. Skipping.\n" "${UI[SKIP]}"; return 1
	elif [[ "$index" -gt "$TASK_COUNT" ]]; then
		printf "%s Task %s does not exist. Skipping.\n" "${UI[SKIP]}" "$index"; return 1
	else return 0; fi
}

print_success_task() {
	local icon="$1" index="$2" task="$3"
	printf "%s %-*d %s\n" "$icon" "$INDEX_WIDTH" "$index" "${task#x }"
}

# SUBCOMMANDS =============================================================== #

todo_help() {
	cat <<-EOF
	USAGE
	  bash todo <command> [<argument>...]

	COMMANDS
	  add   <description>
	  del   <index>...
	  done  <index>...
	  undo  <index>...
	EOF
	exit 0
}

todo_add() {
	local task; task="$(awk '$1=$1' <<< "$*")"
	local index; index="$(( TASK_COUNT + 1 ))"
	printf "%s\n" "$task" >> "$TODO_FILE"
	print_success_task "${UI[ADD]}" "$index" "$task"
}

todo_del() {
	local icon="${ICON_DEL:+$ICON_DEL }"
	local task formatted_task
	local valid_tasks="" sed_args=()

	local i; for i in "$@"; do
		if ! validate_index "$i"; then continue; fi
		sed_args+=("-e" "${i}d")
		task="$(sed -n "${i}p" "$TODO_FILE")"
		formatted_task="$(print_success_task "${UI[DEL]}" "$i" "$task")"
		valid_tasks+="$formatted_task"
	done

	if [[ "${#sed_args[@]}" -gt 0 ]]; then
		sed -i "${sed_args[@]}" "$TODO_FILE"
		printf "%s" "$valid_tasks"
	else exit 2; fi
	is_todo_empty
}

todo_done() {
	local task formatted_task valid_tasks="" sed_args=()

	local i; for i in "$@"; do
		if ! validate_index "$i"; then continue; fi
		task="$(sed -n "${i}p" "$TODO_FILE")"

		if [[ "$task" =~ ^x ]]; then
			printf "⏭️ Task %d is already marked as done. Skipping.\n" "$i"; continue
		fi

		sed_args+=("-e" "${i}s/^/x /")
		formatted_task="$(print_success_task "${UI[DONE]}" "$i" "$task")"
		valid_tasks+="$formatted_task"
	done

	if [[ "${#sed_args[@]}" -gt 0 ]]; then
		sed -i "${sed_args[@]}" "$TODO_FILE"
		printf "%s" "$valid_tasks"
	else exit 2; fi
}

todo_undo() {
	local task formatted_task valid_tasks="" sed_args=()

	local i; for i in "$@"; do
		if ! validate_index "$i"; then continue; fi
		task="$(sed -n "${i}p" "$TODO_FILE")"

		if [[ ! "$task" =~ ^x ]]; then
			printf "Task %d is already unchecked.\n" "$i"; continue
		fi

		sed_args+=("-e" "${i}s/^x //")
		formatted_task="$(print_success_task "${UI[UNDO]}" "$i" "$task")"
		valid_tasks+="$formatted_task"
	done

	if [[ "${#sed_args[@]}" -gt 0 ]]; then
		sed -i "${sed_args[@]}" "$TODO_FILE"
		printf "%s" "$valid_tasks"
	else exit 2; fi
}

# MAIN ====================================================================== #

main() {
	init_storage
	local cmd="${1:-}"; shift

	case "$cmd" in
		--init-only)
			exit 0
			;;
		""|help|--help)
			todo_help
			;;
		add)
			[[ -n "${1:-}" ]] || die 2 "Task description cannot be empty."
			todo_add "$@"
			;;
		del)
			[[ -n "${1:-}" ]] || die 2 "Task index required."
			is_todo_empty
			todo_del "$@"
			;;
		done)
			[[ -n "${1:-}" ]] || die 2 "Task index required."
			is_todo_empty
			todo_done "$@"
			;;
		undo)
			[[ -n "${1:-}" ]] || die 2 "Task index required."
			is_todo_empty
			todo_undo "$@"
			;;
		*)
			die 2 "${cmd} is not a valid command."
			;;
	esac
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	main "$@"
fi
