#!/bin/bash

# ===================================================================================== #
# Description:		Adds tasks to txt file.
# Synopsis:			bin/todo add [+<list-name>] <task>
# ===================================================================================== #



# Settings
# ===================================================================================== #

set -euo pipefail



# Functions
# ===================================================================================== #

check_arg_count() {
	if [[ $# -eq 0 ]]
	then
		echo "error: argument required"
		return 1
	fi
}

get_list() {
	local list="todo"

	if [[ "$1" =~ ^\+[a-z]+$ ]]
	then
		list=${1#\+}
		shift
	fi

	echo "$list"
}

validate_path() {
	local path="$1"
	local name="$2"

	if [[ ! -f $path ]]
	then
		echo "error: '${list}.txt': file not found"
		return 1
	fi
}

add_tasks() {
	local tasks_string="$1"

	printf "%s\n" "$tasks_string" >> "$output_path" \
	&& grep -xq "$tasks_string" "$output_path"
}

main() {
	check_arg_count "$@"

	local list_name
	list_name=$( get_list "$1" )

	local output_path="${DATA_DIR}/${list_name}.txt"
	validate_path "$output_path" "$list_name"

	local raw_tasks="$*"
	local tasks
	tasks=$( format_tasks "$raw_tasks" )

	add_tasks "$tasks" "$output_path"
}



# Point of entry
# ===================================================================================== #

main "$@"
