#!/bin/bash

# ===================================================================================== #
# Description:		Adds tasks to txt file.
# Synopsis:			bin/todo add <task> [+ <task> ...]
# ===================================================================================== #



# Main logic
# ===================================================================================== #

add_tasks() {
	local input_str="$*"
	local new_tasks

	# If no tasks
	while [[ -z $input_str ]]
	do
		read input_str
	done

	# Format tasks
	new_tasks=$(sed "s/[[:space:]]*+[[:space:]]*/\n/g" <<< $input_str)

	# Append tasks to txt file
	printf "%s\n" "$new_tasks" >> $TODO_TXT	\
		&&	grep -xn "$new_tasks" $TODO_TXT	\
		|	awk -F':' '{ printf " + %3d  %s\n", $1, substr($0, index($0, ":") + 1) }'
}



# Point of entry
# ===================================================================================== #

add_tasks "$@"
