#!/bin/bash

# ===================================================================================== #
# Description:		Delete tasks from txt file.
# Synopsis:			bin/todo delete [<list-name>] <task-number> ...
# ===================================================================================== #



# Settings
# ===================================================================================== #

shopt -s extglob



# Main logic
# ===================================================================================== #

delete_tasks() {
	# If no parameters
	while [[ -z $1 ]]
	do
		local input
		read -a input && set -- "${input[@]}"
	done

	local total_deleted_lines=$#
	local file_path="$TODO_TXT"

	local line_count
	local line_count_reduced
	local line_count_result

	if [[ $1 =~ ^[a-z]+$ ]]
	then
		file_path="${DATA_DIR}/${1}.txt"

		if [[ ! -f "$file_path" ]]
		then
			echo "error: '${1}.txt': file not found"
			return 1
		fi

		shift
	fi

	line_count=$(wc -l < $file_path)

	local line_number
	for line_number in "$@"
	do
		if [[ ! $line_number =~ ^[0-9]+$ ]]
		then
			echo "error: '${line_number}' is not an integer"
			return 1

		elif [[ $line_number -eq 0 || $line_number -gt $line_count ]]
		then
			echo "error: line ${line_number} not found"
			return 1

		else
			sed -i "${line_number}d" "$file_path"
		fi
	done

	line_count_reduced=$(( line_count - total_lines ))
	line_count_result=$( wc -l < $file_path )

	if [[ $line_count_result -ne $line_count_reduced ]]
	then
		return 1
	fi
}



# Point of entry
# ===================================================================================== #

delete_tasks "$@"
