#!/bin/bash

# ===================================================================================== #
# Description:		Delete tasks from txt file.
# Synopsis:			bin/todo delete [<list-name>] <task-number> ...
# ===================================================================================== #



# Settings
# ===================================================================================== #

# Extended globbing
shopt -s extglob



# Global variables
# ===================================================================================== #

readonly TXT_DIR="${PROJECT_ROOT}/tests"
readonly TODO_TXT="${TXT_DIR}/todo.txt"



# Main logic
# ===================================================================================== #

delete_task() {
	local file_path=$1
	local line_number=$2

	echo "$file_path line $line_number"

	# Get file length
	# If line number isn't in file
}

parse_delete() {
	local file_path="$TODO_TXT"
	local input

	# If no arguments
	while [[ -z $1 ]]
	do
		read -a input && set -- "${input[@]}"
	done

	while [[ $# -gt 0 ]]
	do
		case $1 in
			# Change file path
			todo|done)
				if [[ -z $2 || ! $2 =~ ^[0-9]*$ ]]
				then
					echo "error: '${1}.txt': task number required"
					return 1
				else
					file_path="${TXT_DIR}/${1}.txt"
					shift
				fi
				;;

			# Main function
			+([0-9]))
				delete_task $file_path $1
				shift
				;;

			# Invalid input
			*)
				echo "error: '$1': invalid argument"
				return 1
				;;
		esac
	done
}



# Point of entry
# ===================================================================================== #

parse_delete "$@"
