#!/bin/bash

# ===================================================================================== #
# Description:		Prints list of tasks.
# Synopsis:			bin/todo list [<list-name>][=<number-limit>] ...
# ===================================================================================== #



# Settings
# ===================================================================================== #

shopt -s extglob



# Global variables
# ===================================================================================== #

DIR_TXT="${PROJECT_ROOT}/tests"



# Main logic
# ===================================================================================== #

print_list() {
	if [[ -n $1 && -n $2 ]]
	then
		local option_str=$1
		local list_title=$2
		local header=""

		# Get list from txt file
		local file_basename=$(tr -d '=0-9' <<< $option_str)
		local file_path="${DIR_TXT}/${file_basename}.txt"
		local file_output=$(cat -n "$file_path")

		# Get list length
		local file_length=$(wc -l < $file_path)
		local length_limit=$(tr -d 'a-z=' <<< $option_str)

		# If length_limit includes entire file
		if [[ $length_limit -ge $file_length ]]
		then
			length_limit=""
		fi

		case $length_limit in
			# If no limit
			"")
				header="$list_title - ALL"
				;;

			# If limit is specified
			+([0-9]))
				header="$list_title - $length_limit LATEST"
				file_output=$(tail -n "$length_limit" <<< "$file_output")
				;;
				
			# Invalid input
			*)
				echo "error: '$length_limit' is not an integer"
				return 1
				;;
		esac

		# Formatted output
		if [[ -n $file_output && -n $header ]]
		then
			cat <<- EOF

			$header

			$file_output

			EOF
		fi
	fi
}

list_tasks() {
	local list_title=""

	# Default options
	if [[ $# -eq 0 ]]
	then
		set -- "$@" "todo"
	fi

	# Parse options
	while [[ $# -gt 0 ]]
	do
		case "$1" in
			# List from todo.txt
			todo|todo=*)
				list_title="TASKS TO DO"
				print_list "$1" "$list_title"
				shift
				;;

			# List from done.txt
			done|done=*)
				list_title="TASKS DONE"
				print_list "$1" "$list_title"
				shift
				;;

			# Invalid option
			*)
				echo "error: '$1': invalid argument"
				return 1
				;;
		esac
	done
}



# Point of entry
# ===================================================================================== #

list_tasks "$@"
