#!/bin/bash

# ===================================================================================== #
# Description:		Prints list of tasks.
# Synopsis:			bin/todo list [<list-name>] [<list-length>]
# ===================================================================================== #



# Settings
# ===================================================================================== #

shopt -s extglob



# Main logic
# ===================================================================================== #

list_tasks() {
	if [[ $# -gt 2 ]]
	then
		echo "error: too many arguments"
		return 1
	fi

	local list_name="todo"
	local list_length=""

	local file_path
	local file_length
	local file_output
	local header

	while [[ $# -gt 0 ]]
	do
		case "$1" in
			0)
				echo "error: list length must be a positive integer"
				return 1 ;;

			+([0-9]))
				list_length=$1
				shift ;;

			+([a-z]))
				list_name=$1
				shift ;;

			*)
				echo "error: '${1}': invalid argument"
				return 1 ;;
		esac
	done

	file_path="${DATA_DIR}/${list_name}.txt"

	if [[ ! -f $file_path ]]
	then
		echo "error: '${list_name}.txt': file not found"
		return 1
	fi

	file_length=$( wc -l < $file_path )

	if [[ $list_length -ge $file_length ]]
	then
		list_length=""
	fi

	case "$list_name" in
		todo)	header="TASKS TO DO" ;;
		done)	header="TASKS DONE" ;;
		*)		header="${^^list_name} TASKS" ;;
	esac

	file_output=$( cat -n "$file_path" )

	if [[ $list_length =~ ^[0-9]+$ ]]
	then
		header+=" | RECENTLY ADDED (${list_length})"
		file_output=$( tail -n "$list_length" <<< "$file_output" )
	else
		header+=" | *"
	fi

	cat <<- EOF

	$header

	$file_output

	EOF
}



# Point of entry
# ===================================================================================== #

list_tasks "$@"
