name: Bash CLI Testing

on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true

      - name: Make script executable
        run: chmod +x ./todo

      - name: Setup Bats
        uses: bats-core/bats-action@4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Bats tests
        env:
          BATS_LIB_PATH: ${{ github.workspace }}/test/test_helper
        run: bats test/
